In [1]:
# pip install torch

In [2]:
import os
import fastf1
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report
import torch


import warnings
warnings.filterwarnings('ignore')

In [3]:
os.makedirs('cache_dir', exist_ok=True)
fastf1.Cache.enable_cache('cache_dir')

years = list(range(2016, 2027))

quali_list = []
race_list = []

for year in years:
    try:
        quali_session = fastf1.get_session(year, 'Italy', 'Q')
        quali_session.load(laps=True, telemetry=True, weather=True)
        quali_results = quali_session.results.copy()
        quali_results['Year'] = year
        quali_list.append(quali_results)
    except Exception as e:
        print(f"Qualifying {year} not available: {e}")

    try:
        race_session = fastf1.get_session(year, 'Italy', 'R')
        race_session.load(laps=True, telemetry=True, weather=True)
        race_results = race_session.results.copy()
        race_results['Year'] = year
        race_list.append(race_results)
    except Exception as e:
        print(f"Race {year} not available: {e}")

quali_df = pd.concat(quali_list, ignore_index=True)
race_df = pd.concat(race_list, ignore_index=True)

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	No cached data found for session_info. Loading data...

_api           INFO 	Fetching session info data...

logger      WARNING 	Failed to load session info data!

core        WARNING 	Cannot load laps, telemetry, weather, and message data because the relevant API is not supported for this session.

core           INFO 	Finished loading data for 21 drivers: ['44', '6', '5', '7', '77', '3', '33', '11', '27', '21', '19', '8', '14', '94', '22', '55', '26', '12', '9', '30', '20']

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	No cached data found for session_info. Loading data...

_api           INFO 	Fetching session info data...

logger      WARNING 	Failed to load session info data!

core        WARNING 	Cannot load laps, telemetry, weather, and message data because the relevant API is not supported for this session.

core           INFO 	Finished loading data for 22 drivers: ['6', '44', '5', '7', '3', '77', '33', '11', '19', '27', '8', '22', '21', '14', '55', '9', '20', '31', '26', '94', '30', '12']

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	No cached data found for session_info. Loading data...

_api           INFO 	Fetching session info data...

logger      WARNING 	Failed to load session info data!

core        WARNING 	Cannot load laps, telemetry, weather, and message data because the relevant API is not supported for this session.

core           INFO 	Finished loading data for 20 drivers: ['44', '33', '3', '18', '31', '77', '7', '5', '19', '2', '11', '27', '14', '26', '55', '20', '30', '9', '94', '8']

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	No cached data found for session_info. Loading data...

_api           INFO 	Fetching session info data...

logger      WARNING 	Failed to load session info data!

core        WARNING 	Cannot load laps, telemetry, weather, and message data because the relevant API is not supported for this session.

core           INFO 	Finished loading data for 20 drivers: ['44', '77', '5', '3', '7', '31', '18', '19', '11', '33', '20', '26', '27', '55', '8', '94', '14', '9', '2', '30']

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['7', '5', '44', '77', '33', '8', '55', '31', '10', '18', '20', '35', '14', '27', '3', '11', '16', '28', '9', '2']

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

logger      WARNING 	Failed to load timing data!

core        WARNING 	Failed to add first lap time from Ergast for drivers: ['7', '44', '33', '77', '8', '55', '31', '18', '35', '14', '10', '20', '11', '16', '2', '27', '3', '5', '9']

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['44', '7', '77', '5', '33', '31', '11', '55', '18', '35', '16', '2', '27', '10', '9', '20', '3', '14', '28', '8']

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['16', '44', '77', '5', '3', '27', '55', '23', '18', '7', '99', '20', '26', '4', '10', '8', '11', '63', '88', '33']

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Driver 16 completed the race distance 00:00.092000 before the recorded end of the session.

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['16', '77', '44', '3', '27', '23', '11', '33', '99', '4', '10', '18', '5', '63', '7', '8', '88', '20', '26', '55']

events      WARNING 	Correcting user input 'Italy' to 'Italian Grand Prix'

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['44', '77', '55', '11', '33', '4', '3', '18', '23', '10', '26', '31', '16', '7', '20', '8', '5', '99', '63', '6']

events      WARNING 	Correcting user input 'Italy' to 'Italian Grand Prix'

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Driver 10 completed the race distance 00:00.067000 before the recorded end of the session.

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['10', '55', '18', '4', '77', '3', '44', '31', '26', '11', '6', '8', '7', '63', '23', '99', '33', '16', '20', '5']

events      WARNING 	Correcting user input 'Italy' to 'Italian Grand Prix'

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['77', '44', '33', '4', '3', '10', '55', '16', '11', '99', '5', '18', '14', '31', '63', '6', '22', '47', '88', '9']

events      WARNING 	Correcting user input 'Italy' to 'Italian Grand Prix'

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 22)

core        WARNING 	Driver 3 completed the race distance 00:00.086000 before the recorded end of the session.

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['3', '4', '77', '16', '11', '55', '18', '14', '63', '31', '6', '5', '99', '88', '47', '9', '44', '33', '10', '22']

events      WARNING 	Correcting user input 'Italy' to 'Italian Grand Prix'

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['16', '1', '55', '11', '44', '63', '4', '3', '10', '14', '31', '77', '45', '24', '22', '6', '5', '18', '20', '47']

events      WARNING 	Correcting user input 'Italy' to 'Italian Grand Prix'

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '55', '44', '11', '4', '10', '45', '24', '31', '47', '77', '22', '6', '20', '3', '18', '14', '5']

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['55', '1', '16', '63', '11', '23', '81', '44', '4', '14', '22', '40', '27', '77', '2', '24', '10', '31', '20', '18']

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 22)

core        WARNING 	Driver 1 completed the race distance 06:25.888000 before the recorded end of the session.

core        WARNING 	Driver 11 completed the race distance 06:19.824000 before the recorded end of the session.

core        WARNING 	Driver 55 completed the race distance 06:14.695000 before the recorded end of the session.

core        WARNING 	Driver 16 completed the race distance 06:14.511000 before the recorded end of the session.

core        WARNING 	Driver 63 completed the race distance 06:07.860000 before the recorded end of the session.

core        WARNING 	Driver 44 completed the race distance 05:48.209000 before the recorded end of the session.

core        WARNING 	Driver 23 completed the race distance 05:40.782000 before the recorded end of the session.

core        WARNING 	Driver 4 completed the race distance 05:40.439000 before the recorded end of the session.

core        WARNING 	Driver 14 completed the race distance 05:39.594000 before the recorded end of the session.

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '44', '23', '4', '14', '77', '40', '81', '2', '24', '10', '18', '27', '20', '31', '22']

events      WARNING 	Correcting user input 'Italy' to 'Italian Grand Prix'

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['4', '81', '63', '16', '55', '44', '1', '11', '23', '27', '14', '3', '20', '10', '31', '22', '18', '43', '77', '24']

events      WARNING 	Correcting user input 'Italy' to 'Italian Grand Prix'

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']

events      WARNING 	Correcting user input 'Italy' to 'Italian Grand Prix'

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '44', '63', '12', '5', '14', '22', '87', '27', '55', '23', '31', '6', '18', '43', '10', '30']

events      WARNING 	Correcting user input 'Italy' to 'Italian Grand Prix'

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '63', '44', '23', '5', '12', '6', '55', '87', '22', '30', '31', '10', '43', '18', '14', '27']

core           INFO 	Loading data for Italian Grand Prix - Qualifying [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 22 drivers: ['10', '63', '81', '16', '44', '3', '12', '43', '1', '41', '5', '87', '27', '30', '55', '31', '22', '23', '77', '11', '14', '18']

core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]

req            INFO 	Using cached data for session_info

req            INFO 	Using cached data for driver_info

req            INFO 	Using cached data for session_status_data

req            INFO 	Using cached data for lap_count

req            INFO 	Using cached data for track_status_data

req            INFO 	Using cached data for _extended_timing_data

req            INFO 	Using cached data for timing_app_data

core           INFO 	Processing timing data...

core        WARNING 	Driver 12 completed the race distance 00:00.013000 before the recorded end of the session.

req            INFO 	Using cached data for car_data

req            INFO 	Using cached data for position_data

req            INFO 	Using cached data for weather_data

req            INFO 	Using cached data for race_control_messages

core           INFO 	Finished loading data for 22 drivers: ['12', '63', '3', '1', '81', '44', '10', '41', '43', '22', '5', '27', '55', '30', '87', '31', '23', '11', '77', '18', '14', '16']

In [4]:
quali_df.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps,Year
0,44,,HAM,hamilton,Mercedes,,mercedes,Lewis,Hamilton,Lewis Hamilton,...,,NaN,0 days 00:01:21.854000,0 days 00:01:21.498000,0 days 00:01:21.135000,NaT,,NaN,NaN,2016
1,6,,ROS,rosberg,Mercedes,,mercedes,Nico,Rosberg,Nico Rosberg,...,,NaN,0 days 00:01:22.497000,0 days 00:01:21.809000,0 days 00:01:21.613000,NaT,,NaN,NaN,2016
2,5,,VET,vettel,Ferrari,,ferrari,Sebastian,Vettel,Sebastian Vettel,...,,NaN,0 days 00:01:23.077000,0 days 00:01:22.275000,0 days 00:01:21.972000,NaT,,NaN,NaN,2016
3,7,,RAI,raikkonen,Ferrari,,ferrari,Kimi,Räikkönen,Kimi Räikkönen,...,,NaN,0 days 00:01:23.217000,0 days 00:01:22.568000,0 days 00:01:22.065000,NaT,,NaN,NaN,2016
4,77,,BOT,bottas,Williams,,williams,Valtteri,Bottas,Valtteri Bottas,...,,NaN,0 days 00:01:23.264000,0 days 00:01:22.499000,0 days 00:01:22.388000,NaT,,NaN,NaN,2016

In [5]:
race_df.head()

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps,Year
0,6,,ROS,rosberg,Mercedes,,mercedes,Nico,Rosberg,Nico Rosberg,...,1,2.0,NaT,NaT,NaT,0 days 01:17:28.089000,Finished,25.0,53.0,2016
1,44,,HAM,hamilton,Mercedes,,mercedes,Lewis,Hamilton,Lewis Hamilton,...,2,1.0,NaT,NaT,NaT,0 days 00:00:15.070000,Finished,18.0,53.0,2016
2,5,,VET,vettel,Ferrari,,ferrari,Sebastian,Vettel,Sebastian Vettel,...,3,3.0,NaT,NaT,NaT,0 days 00:00:20.990000,Finished,15.0,53.0,2016
3,7,,RAI,raikkonen,Ferrari,,ferrari,Kimi,Räikkönen,Kimi Räikkönen,...,4,4.0,NaT,NaT,NaT,0 days 00:00:27.561000,Finished,12.0,53.0,2016
4,3,,RIC,ricciardo,Red Bull,,red_bull,Daniel,Ricciardo,Daniel Ricciardo,...,5,6.0,NaT,NaT,NaT,0 days 00:00:45.295000,Finished,10.0,53.0,2016

    ## Build a per-driver, per-year training dataset
Merge qualifying features with race outcomes so each row is one driver's Monza weekend.

In [6]:
feature_cols = ['Year', 'DriverId', 'Abbreviation', 'TeamName']

quali_feat = quali_df[feature_cols + ['Position', 'Q1', 'Q2', 'Q3']].rename(columns={'Position': 'QualiPosition'})
race_feat = race_df[['Year', 'DriverId', 'GridPosition', 'Position', 'Status', 'Points']].rename(columns={'Position': 'FinishPosition'})

data = quali_feat.merge(race_feat, on=['Year', 'DriverId'], how='inner')

for col in ['Q1', 'Q2', 'Q3']:
    data[col] = data[col].dt.total_seconds()

data['BestQualiTime'] = data[['Q1', 'Q2', 'Q3']].min(axis=1)
data['GapToPole'] = data['BestQualiTime'] - data.groupby('Year')['BestQualiTime'].transform('min')

data = data.dropna(subset=['BestQualiTime', 'GridPosition', 'QualiPosition']).reset_index(drop=True)
print(data.shape)
data.head()

(222, 14)

,Year,DriverId,Abbreviation,TeamName,QualiPosition,Q1,Q2,Q3,GridPosition,FinishPosition,Status,Points,BestQualiTime,GapToPole
0,2016,hamilton,HAM,Mercedes,1.0,81.854,81.498,81.135,1.0,2.0,Finished,18.0,81.135,0.000
1,2016,rosberg,ROS,Mercedes,2.0,82.497,81.809,81.613,2.0,1.0,Finished,25.0,81.613,0.478
2,2016,vettel,VET,Ferrari,3.0,83.077,82.275,81.972,3.0,3.0,Finished,15.0,81.972,0.837
3,2016,raikkonen,RAI,Ferrari,4.0,83.217,82.568,82.065,4.0,4.0,Finished,12.0,82.065,0.930
4,2016,bottas,BOT,Williams,5.0,83.264,82.499,82.388,5.0,6.0,Finished,8.0,82.388,1.253

## Define the classification target
Bucket finishing position by points scored, since that is robust to DNFs/lapped cars without a valid classified position: **Podium** (15+ pts, P1-P3), **Points** (1-12 pts, P4-P10), **No Points** (0 pts, P11+ or DNF).

In [7]:
def points_to_bucket(points):
    if points >= 15:
        return 'Podium'
    if points > 0:
        return 'Points'
    return 'No Points'

data['PlacementBucket'] = data['Points'].apply(points_to_bucket)
data['PlacementBucket'].value_counts()

PlacementBucket
No Points    113
Points        76
Podium        33
Name: count, dtype: int64

## Encode features and split train / holdout
Train on 2016-2025, hold out **2026** as the set we classify (its real result is also known, so this doubles as validation).

In [8]:
model_df = pd.get_dummies(data, columns=['TeamName'], prefix='Team')

target_encoder = LabelEncoder()
model_df['PlacementLabel'] = target_encoder.fit_transform(model_df['PlacementBucket'])

feature_columns = ['QualiPosition', 'GridPosition', 'BestQualiTime', 'GapToPole'] + [c for c in model_df.columns if c.startswith('Team_')]

train_df = model_df[model_df['Year'] < 2026]
test_df = model_df[model_df['Year'] == 2026]

X_train, y_train = train_df[feature_columns], train_df['PlacementLabel']
X_test, y_test = test_df[feature_columns], test_df['PlacementLabel']

X_train.shape, X_test.shape

((200, 27), (22, 27))

## Train and compare models

In [9]:
models = {
    'LogisticRegression': LogisticRegression(max_iter=1000, class_weight='balanced'),
    'RandomForest': RandomForestClassifier(n_estimators=300, max_depth=5, class_weight='balanced', random_state=42),
}

for name, model in models.items():
    cv_scores = cross_val_score(model, X_train, y_train, cv=5)
    model.fit(X_train, y_train)
    test_preds = model.predict(X_test)
    print(f"--- {name} ---")
    print(f"CV accuracy (2016-2025): {cv_scores.mean():.3f} +/- {cv_scores.std():.3f}")
    print(classification_report(y_test, test_preds, target_names=target_encoder.classes_, zero_division=0))

--- LogisticRegression ---
CV accuracy (2016-2025): 0.690 +/- 0.075
              precision    recall  f1-score   support

   No Points       0.90      0.75      0.82        12
      Podium       0.29      0.67      0.40         3
      Points       0.40      0.29      0.33         7

    accuracy                           0.59        22
   macro avg       0.53      0.57      0.52        22
weighted avg       0.66      0.59      0.61        22

--- RandomForest ---
CV accuracy (2016-2025): 0.690 +/- 0.098
              precision    recall  f1-score   support

   No Points       0.91      0.83      0.87        12
      Podium       0.20      0.33      0.25         3
      Points       0.50      0.43      0.46         7

    accuracy                           0.64        22
   macro avg       0.54      0.53      0.53        22
weighted avg       0.68      0.64      0.66        22

## Classify the 2026 Monza grid

In [10]:
best_model = models['RandomForest']
test_probs = best_model.predict_proba(X_test)

results_2026 = test_df[['Abbreviation', 'PlacementBucket']].copy()
results_2026['PredictedBucket'] = target_encoder.inverse_transform(best_model.predict(X_test))
for i, cls in enumerate(target_encoder.classes_):
    results_2026[f'P({cls})'] = test_probs[:, i]

bucket_order = ['Podium', 'Points', 'No Points']
results_2026['PredictedBucket'] = pd.Categorical(results_2026['PredictedBucket'], categories=bucket_order, ordered=True)

results_2026.sort_values(['PredictedBucket', 'P(Podium)'], ascending=[True, False]).reset_index(drop=True)

,Abbreviation,PlacementBucket,PredictedBucket,P(No Points),P(Podium),P(Points)
0,RUS,Podium,Podium,0.030546,0.807019,0.162435
1,GAS,Points,Podium,0.066115,0.772234,0.161651
2,LEC,No Points,Podium,0.081636,0.581311,0.337053
3,PIA,Points,Podium,0.159112,0.465960,0.374928
4,HAM,Points,Podium,0.101185,0.461985,0.436830
5,VER,Podium,Points,0.118707,0.386190,0.495104
6,ANT,Podium,Points,0.153663,0.352799,0.493539
7,COL,Points,Points,0.158542,0.245178,0.596279
8,NOR,Points,Points,0.270661,0.187793,0.541546
9,LIN,Points,Points,0.341911,0.143801,0.514287
10,BOR,No Points,Points,0.394807,0.124018,0.481175
11,HUL,No Points,No Points,0.518732,0.082862,0.398406
12,LAW,No Points,No Points,0.566273,0.080624,0.353102
13,BEA,No Points,No Points,0.638851,0.059174,0.301975
14,SAI,No Points,No Points,0.602048,0.024338,0.373614
15,TSU,Points,No Points,0.780809,0.019091,0.200100
16,OCO,No Points,No Points,0.778500,0.016488,0.205013
17,PER,No Points,No Points,0.869404,0.015441,0.115155
18,BOT,No Points,No Points,0.863300,0.015070,0.121630
19,ALO,No Points,No Points,0.889987,0.012001,0.098012
20,STR,No Points,No Points,0.888404,0.011668,0.099928
21,ALB,No Points,No Points,0.848787,0.010316,0.140897

## Yeee no. STH aint right...